name: Build, publish and deploy to MonsterASP

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86

      - name: Deploy to MonsterASP
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.site82883 }}
          server-computer-name: ${{ secrets.site82883.siteasp.net }}
          server-username: ${{ secrets.site82883 }}
          server-password: ${{ secrets.Xj5+_Rh9Me7? }}
